-- Stores the pre-computed elevation profile for a race day.
-- Generated by tools/gpx-to-profile/index.js from a GPX file.
--
-- Schema:
--   {
--     "distance":      float,   -- km, 1 decimal
--     "elevationGain": int,     -- metres, 3 m hysteresis threshold
--     "elevationLoss": int,     -- metres, 3 m hysteresis threshold
--     "minElevation":  int,     -- metres
--     "maxElevation":  int,     -- metres
--     "points": [{ "km": float, "alt": int }, ...]   -- 150-250 points
--   }
ALTER TABLE race_days
  ADD COLUMN IF NOT EXISTS "elevationProfile" JSONB;
