-- Observabilidad privada y controles manuales para las automatizaciones del VPS.
-- Las tablas públicas race_uci_* permanecen sin cambios porque forman parte del
-- contrato de datos consumido por las aplicaciones.

ALTER TABLE private.uci_results_manual_queue RENAME TO results_manual_queue;
ALTER SEQUENCE private.uci_results_manual_queue_id_seq RENAME TO results_manual_queue_id_seq;
ALTER INDEX private.uci_results_manual_queue_race_id_idx RENAME TO results_manual_queue_race_id_idx;
ALTER INDEX private.uci_results_manual_queue_claim_idx RENAME TO results_manual_queue_claim_idx;

-- Esta función de reparación ya existía y captura la cola dentro de su snapshot.
-- Su cuerpo PL/pgSQL se actualiza al nuevo nombre sin alterar el resto del contrato.
DO $migration$
DECLARE
  v_definition text;
BEGIN
  SELECT pg_catalog.pg_get_functiondef(
    'private.delete_invalid_results_race(text,text,text)'::regprocedure
  ) INTO v_definition;
  EXECUTE pg_catalog.replace(
    v_definition,
    'private.uci_results_manual_queue',
    'private.results_manual_queue'
  );
END;
$migration$;

ALTER TABLE private.results_manual_queue ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE private.results_manual_queue FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON SEQUENCE private.results_manual_queue_id_seq FROM PUBLIC, anon, authenticated, service_role;

CREATE TABLE private.broadcasts_manual_queue (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requested_at timestamptz NOT NULL DEFAULT now(),
  requested_by uuid,
  started_at timestamptz,
  finished_at timestamptz,
  attempts integer NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'running', 'done', 'error')),
  error_message text
);

ALTER TABLE private.broadcasts_manual_queue ENABLE ROW LEVEL SECURITY;
CREATE INDEX broadcasts_manual_queue_claim_idx
  ON private.broadcasts_manual_queue (status, requested_at, id)
  WHERE status IN ('pending', 'running');
REVOKE ALL ON TABLE private.broadcasts_manual_queue FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON SEQUENCE private.broadcasts_manual_queue_id_seq FROM PUBLIC, anon, authenticated, service_role;

CREATE TABLE private.automation_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job text NOT NULL CHECK (job IN ('results', 'broadcasts', 'uci_team_ranking')),
  trigger_kind text NOT NULL CHECK (trigger_kind IN ('scheduled', 'manual', 'scheduled_manual')),
  request_id bigint,
  revision text,
  started_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz,
  status text NOT NULL DEFAULT 'running'
    CHECK (status IN ('running', 'success', 'noop', 'partial', 'error')),
  summary jsonb NOT NULL DEFAULT '{}'::jsonb,
  error_message text
);

ALTER TABLE private.automation_runs ENABLE ROW LEVEL SECURITY;
CREATE INDEX automation_runs_job_started_idx
  ON private.automation_runs (job, started_at DESC);
CREATE INDEX automation_runs_running_idx
  ON private.automation_runs (started_at)
  WHERE status = 'running';
REVOKE ALL ON TABLE private.automation_runs FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON SEQUENCE private.automation_runs_id_seq FROM PUBLIC, anon, authenticated, service_role;

CREATE TABLE private.automation_source_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id bigint NOT NULL REFERENCES private.automation_runs(id) ON DELETE CASCADE,
  source text NOT NULL,
  status text NOT NULL CHECK (status IN ('success', 'noop', 'warning', 'error')),
  items_found integer NOT NULL DEFAULT 0 CHECK (items_found >= 0),
  items_matched integer NOT NULL DEFAULT 0 CHECK (items_matched >= 0),
  items_changed integer NOT NULL DEFAULT 0 CHECK (items_changed >= 0),
  errors integer NOT NULL DEFAULT 0 CHECK (errors >= 0),
  summary jsonb NOT NULL DEFAULT '{}'::jsonb,
  UNIQUE (run_id, source)
);

ALTER TABLE private.automation_source_runs ENABLE ROW LEVEL SECURITY;
CREATE INDEX automation_source_runs_source_idx
  ON private.automation_source_runs (source, run_id DESC);
REVOKE ALL ON TABLE private.automation_source_runs FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON SEQUENCE private.automation_source_runs_id_seq FROM PUBLIC, anon, authenticated, service_role;

CREATE OR REPLACE FUNCTION private.dispatch_results_sync(
  p_race_id text,
  p_stage integer,
  p_ignore_window boolean
)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
BEGIN
  IF NOT (SELECT private.is_admin()) THEN
    RAISE EXCEPTION 'La operación requiere permisos de administración' USING ERRCODE = '42501';
  END IF;
  IF p_race_id IS NOT NULL AND btrim(p_race_id) = '' THEN
    RAISE EXCEPTION 'Falta p_race_id';
  END IF;
  IF p_stage IS NOT NULL AND p_race_id IS NULL THEN
    RAISE EXCEPTION 'Una etapa requiere p_race_id';
  END IF;
  IF p_race_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.races WHERE id = p_race_id
  ) THEN
    RAISE EXCEPTION 'Carrera inexistente: %', p_race_id;
  END IF;

  PERFORM pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtext('results_manual_queue'));
  IF NOT EXISTS (
    SELECT 1
    FROM private.results_manual_queue q
    WHERE q.status IN ('pending', 'running')
      AND q.race_id IS NOT DISTINCT FROM p_race_id
      AND q.stage_number IS NOT DISTINCT FROM p_stage
      AND q.ignore_window = COALESCE(p_ignore_window, false)
  ) THEN
    INSERT INTO private.results_manual_queue (
      race_id, stage_number, ignore_window, requested_by
    ) VALUES (
      p_race_id, p_stage, COALESCE(p_ignore_window, false), (SELECT auth.uid())
    );
  END IF;

  RETURN 'queued';
END;
$function$;

CREATE OR REPLACE FUNCTION private.claim_results_manual_request()
RETURNS TABLE (
  request_id bigint,
  race_id text,
  stage_number integer,
  ignore_window boolean
)
LANGUAGE sql
SECURITY DEFINER
SET search_path = ''
AS $function$
  WITH candidate AS (
    SELECT q.id
    FROM private.results_manual_queue q
    WHERE q.status = 'pending'
       OR (q.status = 'running' AND q.started_at < now() - interval '30 minutes')
    ORDER BY q.requested_at, q.id
    FOR UPDATE SKIP LOCKED
    LIMIT 1
  ), claimed AS (
    UPDATE private.results_manual_queue q
    SET status = 'running',
        started_at = now(),
        finished_at = NULL,
        attempts = q.attempts + 1,
        error_message = NULL
    FROM candidate c
    WHERE q.id = c.id
    RETURNING q.id, q.race_id, q.stage_number, q.ignore_window
  )
  SELECT id, race_id, stage_number, ignore_window FROM claimed;
$function$;

CREATE OR REPLACE FUNCTION private.finish_results_manual_request(
  p_request_id bigint,
  p_success boolean,
  p_error text DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
BEGIN
  UPDATE private.results_manual_queue
  SET status = CASE WHEN p_success THEN 'done' ELSE 'error' END,
      finished_at = now(),
      error_message = CASE WHEN p_success THEN NULL ELSE left(COALESCE(p_error, 'Error sin detalle'), 1000) END
  WHERE id = p_request_id
    AND status = 'running';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Solicitud manual no reclamada: %', p_request_id;
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION private.dispatch_broadcasts_sync()
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
BEGIN
  IF NOT (SELECT private.is_admin()) THEN
    RAISE EXCEPTION 'La operación requiere permisos de administración' USING ERRCODE = '42501';
  END IF;

  PERFORM pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtext('broadcasts_manual_queue'));
  IF NOT EXISTS (
    SELECT 1 FROM private.broadcasts_manual_queue
    WHERE status IN ('pending', 'running')
  ) THEN
    INSERT INTO private.broadcasts_manual_queue (requested_by)
    VALUES ((SELECT auth.uid()));
  END IF;

  RETURN 'queued';
END;
$function$;

CREATE OR REPLACE FUNCTION private.claim_broadcasts_manual_request()
RETURNS TABLE (request_id bigint)
LANGUAGE sql
SECURITY DEFINER
SET search_path = ''
AS $function$
  WITH candidate AS (
    SELECT q.id
    FROM private.broadcasts_manual_queue q
    WHERE q.status = 'pending'
       OR (q.status = 'running' AND q.started_at < now() - interval '30 minutes')
    ORDER BY q.requested_at, q.id
    FOR UPDATE SKIP LOCKED
    LIMIT 1
  ), claimed AS (
    UPDATE private.broadcasts_manual_queue q
    SET status = 'running',
        started_at = now(),
        finished_at = NULL,
        attempts = q.attempts + 1,
        error_message = NULL
    FROM candidate c
    WHERE q.id = c.id
    RETURNING q.id
  )
  SELECT id FROM claimed;
$function$;

CREATE OR REPLACE FUNCTION private.finish_broadcasts_manual_request(
  p_request_id bigint,
  p_success boolean,
  p_error text DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
BEGIN
  UPDATE private.broadcasts_manual_queue
  SET status = CASE WHEN p_success THEN 'done' ELSE 'error' END,
      finished_at = now(),
      error_message = CASE WHEN p_success THEN NULL ELSE left(COALESCE(p_error, 'Error sin detalle'), 1000) END
  WHERE id = p_request_id
    AND status = 'running';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Solicitud manual no reclamada: %', p_request_id;
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION private.start_automation_run(
  p_job text,
  p_trigger_kind text,
  p_request_id bigint DEFAULT NULL,
  p_revision text DEFAULT NULL
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
DECLARE
  v_id bigint;
BEGIN
  IF session_user = 'cc_results_worker' AND p_job NOT IN ('results', 'uci_team_ranking') THEN
    RAISE EXCEPTION 'Trabajo no autorizado para cc_results_worker' USING ERRCODE = '42501';
  ELSIF session_user = 'cc_broadcasts_login' AND p_job <> 'broadcasts' THEN
    RAISE EXCEPTION 'Trabajo no autorizado para cc_broadcasts_login' USING ERRCODE = '42501';
  ELSIF session_user NOT IN ('cc_results_worker', 'cc_broadcasts_login') THEN
    RAISE EXCEPTION 'Worker no autorizado' USING ERRCODE = '42501';
  END IF;

  INSERT INTO private.automation_runs (job, trigger_kind, request_id, revision)
  VALUES (p_job, p_trigger_kind, p_request_id, NULLIF(left(p_revision, 80), ''))
  RETURNING id INTO v_id;
  RETURN v_id;
END;
$function$;

CREATE OR REPLACE FUNCTION private.record_automation_source_run(
  p_run_id bigint,
  p_source text,
  p_status text,
  p_items_found integer DEFAULT 0,
  p_items_matched integer DEFAULT 0,
  p_items_changed integer DEFAULT 0,
  p_errors integer DEFAULT 0,
  p_summary jsonb DEFAULT '{}'::jsonb
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
DECLARE
  v_job text;
BEGIN
  SELECT job INTO v_job FROM private.automation_runs WHERE id = p_run_id;
  IF (session_user = 'cc_results_worker' AND v_job NOT IN ('results', 'uci_team_ranking'))
     OR (session_user = 'cc_broadcasts_login' AND v_job <> 'broadcasts')
     OR session_user NOT IN ('cc_results_worker', 'cc_broadcasts_login') THEN
    RAISE EXCEPTION 'Ejecución no autorizada para este worker' USING ERRCODE = '42501';
  END IF;

  INSERT INTO private.automation_source_runs (
    run_id, source, status, items_found, items_matched, items_changed, errors, summary
  ) VALUES (
    p_run_id, p_source, p_status, p_items_found, p_items_matched,
    p_items_changed, p_errors, COALESCE(p_summary, '{}'::jsonb)
  )
  ON CONFLICT (run_id, source) DO UPDATE SET
    status = EXCLUDED.status,
    items_found = EXCLUDED.items_found,
    items_matched = EXCLUDED.items_matched,
    items_changed = EXCLUDED.items_changed,
    errors = EXCLUDED.errors,
    summary = EXCLUDED.summary;
END;
$function$;

CREATE OR REPLACE FUNCTION private.finish_automation_run(
  p_run_id bigint,
  p_status text,
  p_summary jsonb DEFAULT '{}'::jsonb,
  p_error text DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
DECLARE
  v_job text;
BEGIN
  SELECT job INTO v_job FROM private.automation_runs WHERE id = p_run_id;
  IF (session_user = 'cc_results_worker' AND v_job NOT IN ('results', 'uci_team_ranking'))
     OR (session_user = 'cc_broadcasts_login' AND v_job <> 'broadcasts')
     OR session_user NOT IN ('cc_results_worker', 'cc_broadcasts_login') THEN
    RAISE EXCEPTION 'Ejecución no autorizada para este worker' USING ERRCODE = '42501';
  END IF;

  UPDATE private.automation_runs
  SET finished_at = now(),
      status = p_status,
      summary = COALESCE(p_summary, '{}'::jsonb),
      error_message = CASE WHEN p_status IN ('error', 'partial')
        THEN left(COALESCE(p_error, 'Error sin detalle'), 2000)
        ELSE NULL
      END
  WHERE id = p_run_id
    AND status = 'running';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Ejecución no activa: %', p_run_id;
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION private.broadcasts_sync_due()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = ''
AS $function$
  SELECT NOT EXISTS (
    SELECT 1
    FROM private.automation_runs
    WHERE job = 'broadcasts'
      AND status IN ('running', 'success', 'noop', 'partial')
      AND started_at >= now() - interval '29 minutes'
  );
$function$;

CREATE OR REPLACE FUNCTION private.get_automation_monitor()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
STABLE
SET search_path = ''
AS $function$
DECLARE
  v_result jsonb;
BEGIN
  IF NOT (SELECT private.is_admin()) THEN
    RAISE EXCEPTION 'La operación requiere permisos de administración' USING ERRCODE = '42501';
  END IF;

  SELECT jsonb_build_object(
    'generatedAt', now(),
    'runs', COALESCE((
      SELECT jsonb_agg(to_jsonb(recent) ORDER BY recent."startedAt" DESC)
      FROM (
        SELECT id, job, trigger_kind AS "triggerKind", request_id AS "requestId",
               revision, started_at AS "startedAt", finished_at AS "finishedAt",
               status, summary, error_message AS "errorMessage"
        FROM private.automation_runs
        ORDER BY started_at DESC
        LIMIT 100
      ) recent
    ), '[]'::jsonb),
    'sources', COALESCE((
      SELECT jsonb_agg(to_jsonb(recent_sources) ORDER BY recent_sources."startedAt" DESC, recent_sources.source)
      FROM (
        SELECT s.run_id AS "runId", r.started_at AS "startedAt", s.source, s.status,
               s.items_found AS "itemsFound", s.items_matched AS "itemsMatched",
               s.items_changed AS "itemsChanged", s.errors, s.summary
        FROM private.automation_source_runs s
        JOIN private.automation_runs r ON r.id = s.run_id
        ORDER BY r.started_at DESC, s.source
        LIMIT 300
      ) recent_sources
    ), '[]'::jsonb),
    'queues', jsonb_build_object(
      'results', jsonb_build_object(
        'pending', (SELECT count(*) FROM private.results_manual_queue WHERE status = 'pending'),
        'running', (SELECT count(*) FROM private.results_manual_queue WHERE status = 'running'),
        'lastRequest', (SELECT to_jsonb(q) FROM (
          SELECT id, race_id AS "raceId", stage_number AS "stageNumber", requested_at AS "requestedAt",
                 started_at AS "startedAt", finished_at AS "finishedAt", status, error_message AS "errorMessage"
          FROM private.results_manual_queue ORDER BY requested_at DESC, id DESC LIMIT 1
        ) q)
      ),
      'broadcasts', jsonb_build_object(
        'pending', (SELECT count(*) FROM private.broadcasts_manual_queue WHERE status = 'pending'),
        'running', (SELECT count(*) FROM private.broadcasts_manual_queue WHERE status = 'running'),
        'lastRequest', (SELECT to_jsonb(q) FROM (
          SELECT id, requested_at AS "requestedAt", started_at AS "startedAt",
                 finished_at AS "finishedAt", status, error_message AS "errorMessage"
          FROM private.broadcasts_manual_queue ORDER BY requested_at DESC, id DESC LIMIT 1
        ) q)
      )
    )
  ) INTO v_result;

  RETURN v_result;
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_trigger_results_sync()
RETURNS text
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $function$
BEGIN
  IF NOT (SELECT private.is_admin()) THEN
    RAISE EXCEPTION 'La operación requiere permisos de administración' USING ERRCODE = '42501';
  END IF;
  RETURN private.dispatch_results_sync(NULL, NULL, true);
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_trigger_results_sync(p_race_id text)
RETURNS text
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $function$
BEGIN
  IF NOT (SELECT private.is_admin()) THEN
    RAISE EXCEPTION 'La operación requiere permisos de administración' USING ERRCODE = '42501';
  END IF;
  RETURN private.dispatch_results_sync(p_race_id, NULL, false);
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_trigger_results_sync(p_race_id text, p_stage integer)
RETURNS text
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $function$
BEGIN
  IF NOT (SELECT private.is_admin()) THEN
    RAISE EXCEPTION 'La operación requiere permisos de administración' USING ERRCODE = '42501';
  END IF;
  RETURN private.dispatch_results_sync(p_race_id, p_stage, false);
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_trigger_broadcasts_sync()
RETURNS text
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $function$
BEGIN
  IF NOT (SELECT private.is_admin()) THEN
    RAISE EXCEPTION 'La operación requiere permisos de administración' USING ERRCODE = '42501';
  END IF;
  RETURN private.dispatch_broadcasts_sync();
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_get_automation_monitor()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY INVOKER
STABLE
SET search_path = ''
AS $function$
BEGIN
  IF NOT (SELECT private.is_admin()) THEN
    RAISE EXCEPTION 'La operación requiere permisos de administración' USING ERRCODE = '42501';
  END IF;
  RETURN private.get_automation_monitor();
END;
$function$;

REVOKE ALL ON FUNCTION private.dispatch_uci_results_workflow(text, integer, boolean) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.claim_uci_results_manual_request() FROM PUBLIC, anon, authenticated, service_role, cc_results_worker;
REVOKE ALL ON FUNCTION private.finish_uci_results_manual_request(bigint, boolean, text) FROM PUBLIC, anon, authenticated, service_role, cc_results_worker;
DROP FUNCTION private.dispatch_uci_results_workflow(text, integer, boolean);
DROP FUNCTION private.claim_uci_results_manual_request();
DROP FUNCTION private.finish_uci_results_manual_request(bigint, boolean, text);

REVOKE ALL ON FUNCTION public.admin_trigger_uci_results_workflow() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.admin_trigger_uci_results_workflow(text) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.admin_trigger_uci_results_workflow(text, integer) FROM PUBLIC, anon, authenticated, service_role;
DROP FUNCTION public.admin_trigger_uci_results_workflow();
DROP FUNCTION public.admin_trigger_uci_results_workflow(text);
DROP FUNCTION public.admin_trigger_uci_results_workflow(text, integer);

REVOKE ALL ON FUNCTION private.dispatch_results_sync(text, integer, boolean) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.claim_results_manual_request() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.finish_results_manual_request(bigint, boolean, text) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.dispatch_broadcasts_sync() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.claim_broadcasts_manual_request() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.finish_broadcasts_manual_request(bigint, boolean, text) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.start_automation_run(text, text, bigint, text) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.record_automation_source_run(bigint, text, text, integer, integer, integer, integer, jsonb) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.finish_automation_run(bigint, text, jsonb, text) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.broadcasts_sync_due() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION private.get_automation_monitor() FROM PUBLIC, anon, authenticated, service_role;

GRANT EXECUTE ON FUNCTION private.dispatch_results_sync(text, integer, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION private.dispatch_broadcasts_sync() TO authenticated;
GRANT EXECUTE ON FUNCTION private.get_automation_monitor() TO authenticated;

GRANT EXECUTE ON FUNCTION private.claim_results_manual_request() TO cc_results_worker;
GRANT EXECUTE ON FUNCTION private.finish_results_manual_request(bigint, boolean, text) TO cc_results_worker;
GRANT EXECUTE ON FUNCTION private.start_automation_run(text, text, bigint, text) TO cc_results_worker, cc_broadcasts_worker;
GRANT EXECUTE ON FUNCTION private.record_automation_source_run(bigint, text, text, integer, integer, integer, integer, jsonb)
  TO cc_results_worker, cc_broadcasts_worker;
GRANT EXECUTE ON FUNCTION private.finish_automation_run(bigint, text, jsonb, text) TO cc_results_worker, cc_broadcasts_worker;
GRANT EXECUTE ON FUNCTION private.claim_broadcasts_manual_request() TO cc_broadcasts_worker;
GRANT EXECUTE ON FUNCTION private.finish_broadcasts_manual_request(bigint, boolean, text) TO cc_broadcasts_worker;
GRANT EXECUTE ON FUNCTION private.broadcasts_sync_due() TO cc_broadcasts_worker;

REVOKE ALL ON FUNCTION public.admin_trigger_results_sync() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.admin_trigger_results_sync(text) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.admin_trigger_results_sync(text, integer) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.admin_trigger_broadcasts_sync() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.admin_get_automation_monitor() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.admin_trigger_results_sync() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_trigger_results_sync(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_trigger_results_sync(text, integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_trigger_broadcasts_sync() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_get_automation_monitor() TO authenticated;

COMMENT ON TABLE private.automation_runs IS
  'Histórico de ejecuciones de las automatizaciones del VPS para el monitor administrativo.';
COMMENT ON TABLE private.automation_source_runs IS
  'Detalle por fuente de cada ejecución observada por el monitor administrativo.';
COMMENT ON FUNCTION public.admin_trigger_results_sync() IS
  'Encola una pasada global de resultados en el VPS sin alterar las tablas race_uci_*.';
COMMENT ON FUNCTION public.admin_trigger_broadcasts_sync() IS
  'Encola una pasada completa de fuentes oficiales de emisiones en el VPS.';
