-- Recuperada el 2026-09-28 de supabase_migrations.schema_migrations.statements
-- (versión 20260606135546, nombre restore_game_schema_simulador). Texto aplicado en producción, sin cambios.

CREATE SCHEMA IF NOT EXISTS game;

CREATE TABLE IF NOT EXISTS game.rider_ratings (
  "riderId"       text    NOT NULL,
  gender          text    NOT NULL,
  archetype       text,
  flat            smallint,
  hill            smallint,
  "medMountain"   smallint,
  "highMountain"  smallint,
  itt             smallint,
  prologue        smallint,
  cobbles         smallint,
  sprint          smallint,
  accel           smallint,
  endurance       smallint,
  "recovDay"      smallint,
  "recovLong"     smallint,
  descending      smallint,
  positioning     smallint,
  handling        smallint,
  experience      smallint,
  aggression      smallint,
  headcraft       smallint,
  notes           text,
  source          text    NOT NULL DEFAULT 'manual',
  verified        boolean NOT NULL DEFAULT false,
  "createdAt"     timestamptz NOT NULL DEFAULT now(),
  "updatedAt"     timestamptz NOT NULL DEFAULT now(),
  role            text,
  "roleDefault"   text,
  CONSTRAINT rider_ratings_pkey PRIMARY KEY ("riderId", gender),
  CONSTRAINT rider_ratings_gender_check       CHECK (gender = ANY (ARRAY['M'::text,'W'::text])),
  CONSTRAINT rider_ratings_flat_check         CHECK (flat         >= 0 AND flat         <= 99),
  CONSTRAINT rider_ratings_hill_check         CHECK (hill         >= 0 AND hill         <= 99),
  CONSTRAINT "rider_ratings_medMountain_check"  CHECK ("medMountain"  >= 0 AND "medMountain"  <= 99),
  CONSTRAINT "rider_ratings_highMountain_check" CHECK ("highMountain" >= 0 AND "highMountain" <= 99),
  CONSTRAINT rider_ratings_itt_check          CHECK (itt          >= 0 AND itt          <= 99),
  CONSTRAINT rider_ratings_prologue_check     CHECK (prologue     >= 0 AND prologue     <= 99),
  CONSTRAINT rider_ratings_cobbles_check      CHECK (cobbles      >= 0 AND cobbles      <= 99),
  CONSTRAINT rider_ratings_sprint_check       CHECK (sprint       >= 0 AND sprint       <= 99),
  CONSTRAINT rider_ratings_accel_check        CHECK (accel        >= 0 AND accel        <= 99),
  CONSTRAINT rider_ratings_endurance_check    CHECK (endurance    >= 0 AND endurance    <= 99),
  CONSTRAINT "rider_ratings_recovDay_check"     CHECK ("recovDay"   >= 0 AND "recovDay"   <= 99),
  CONSTRAINT "rider_ratings_recovLong_check"    CHECK ("recovLong"  >= 0 AND "recovLong"  <= 99),
  CONSTRAINT rider_ratings_descending_check   CHECK (descending   >= 0 AND descending   <= 99),
  CONSTRAINT rider_ratings_positioning_check  CHECK (positioning  >= 0 AND positioning  <= 99),
  CONSTRAINT rider_ratings_handling_check     CHECK (handling     >= 0 AND handling     <= 99),
  CONSTRAINT rider_ratings_experience_check   CHECK (experience   >= 0 AND experience   <= 99),
  CONSTRAINT rider_ratings_aggression_check   CHECK (aggression   >= 0 AND aggression   <= 99),
  CONSTRAINT rider_ratings_headcraft_check    CHECK (headcraft    >= 0 AND headcraft    <= 99)
);

CREATE TABLE IF NOT EXISTS game.race_roles (
  "raceId"      text    NOT NULL,
  "riderId"     text    NOT NULL,
  gender        text    NOT NULL DEFAULT 'M',
  rol           text    NOT NULL,
  "rolDefault"  text,
  source        text    NOT NULL DEFAULT 'roles_auto',
  notes         text,
  "createdAt"   timestamptz NOT NULL DEFAULT now(),
  "updatedAt"   timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT race_roles_pkey PRIMARY KEY ("raceId", "riderId", gender),
  CONSTRAINT race_roles_rol_check        CHECK (rol          = ANY (ARRAY['lider'::text,'sprinter'::text,'colider'::text,'lanzador'::text,'fuga'::text,'rodador'::text,'gregario'::text,'libre'::text])),
  CONSTRAINT "race_roles_rolDefault_check" CHECK ("rolDefault" = ANY (ARRAY['lider'::text,'sprinter'::text,'colider'::text,'lanzador'::text,'fuga'::text,'rodador'::text,'gregario'::text,'libre'::text]))
);

CREATE TABLE IF NOT EXISTS game.race_sim (
  "raceId"        text    NOT NULL,
  seed            integer NOT NULL,
  "engineVersion" text    NOT NULL,
  "tempC"         numeric,
  wet             boolean NOT NULL DEFAULT false,
  finale          text,
  "ganadorId"     text,
  "ganadorNombre" text,
  "censoMeta"     integer,
  texto           text,
  hitos           jsonb,
  log             jsonb,
  clasificacion   jsonb,
  censos          jsonb,
  "createdAt"     timestamptz NOT NULL DEFAULT now(),
  "updatedAt"     timestamptz NOT NULL DEFAULT now(),
  wind            numeric,
  escenario       text,
  "ganadorEquipo" text,
  dnf             jsonb,
  "estadosVivo"   jsonb,
  CONSTRAINT race_sim_pkey PRIMARY KEY ("raceId", seed, "engineVersion")
);
