#!/bin/sh
set -e

# Materializa los archivos con secrets que están en .gitignore desde
# variables de entorno del workflow de Xcode Cloud.

: "${SUPABASE_URL:?SUPABASE_URL environment variable not set in Xcode Cloud}"
: "${SUPABASE_ANON_KEY:?SUPABASE_ANON_KEY environment variable not set in Xcode Cloud}"
: "${GOOGLE_SERVICE_INFO_PLIST_B64:?GOOGLE_SERVICE_INFO_PLIST_B64 environment variable not set in Xcode Cloud}"
: "${CI_PRIMARY_REPOSITORY_PATH:?CI_PRIMARY_REPOSITORY_PATH not set (run from Xcode Cloud)}"

REPO="${CI_PRIMARY_REPOSITORY_PATH}"

# --- Supabase.xcconfig -------------------------------------------------------

CONFIG_DIR="${REPO}/ios-app/Config"
CONFIG_FILE="${CONFIG_DIR}/Supabase.xcconfig"

mkdir -p "${CONFIG_DIR}"

# xcconfig trata '//' como inicio de comentario. El truco $() (interpolación
# vacía) parte el esquema para que Xcode lea la URL como https://...
escaped_url=$(printf '%s' "${SUPABASE_URL}" | sed 's|://|:/$()/|')

cat > "${CONFIG_FILE}" <<EOF
// Generated by ci_scripts/ci_pre_xcodebuild.sh — do not edit.
SUPABASE_URL = ${escaped_url}
SUPABASE_ANON_KEY = ${SUPABASE_ANON_KEY}
EOF

echo "Wrote ${CONFIG_FILE}"

# --- GoogleService-Info.plist ------------------------------------------------

PLIST_DIR="${REPO}/ios-app/CalendarioCiclismo"
PLIST_FILE="${PLIST_DIR}/GoogleService-Info.plist"

mkdir -p "${PLIST_DIR}"
printf '%s' "${GOOGLE_SERVICE_INFO_PLIST_B64}" | base64 --decode > "${PLIST_FILE}"

echo "Wrote ${PLIST_FILE}"

# --- BundledLogos ------------------------------------------------------------
#
# Los logos de carreras son obras de terceros: NO se redistribuyen en el repo
# (están en .gitignore desde la preparación del repo público). Se reconstruyen
# aquí desde `races.logoUrl` en Supabase, la fuente de verdad — igual que
# `scripts/fetch-logos.mjs` en local y que `bundle-logos.yml`.
#
# El proyecto referencia BundledLogos como CARPETA (type: folder), así que el
# build empaqueta lo que haya en disco: si esta descarga falla, el bundle queda
# con lo que tuviera (o vacío) y las apps cargan los logos de red. Por eso todo
# el bloque es NO BLOQUEANTE (`|| true`): nunca debe tumbar el build.
#
# Hash del nombre de fichero idéntico a CacheManager.swift (sha1(url)[:20] + ext).

LOGOS_DIR="${REPO}/ios-app/CalendarioCiclismo/BundledLogos"
mkdir -p "${LOGOS_DIR}"

SUPABASE_URL="${SUPABASE_URL}" SUPABASE_ANON_KEY="${SUPABASE_ANON_KEY}" LOGOS_DIR="${LOGOS_DIR}" \
python3 <<'PYEOF' || true
import hashlib, json, os, sys, urllib.parse
from pathlib import Path
from urllib.request import Request, urlopen

BASE = os.environ["SUPABASE_URL"].rstrip("/")
KEY  = os.environ["SUPABASE_ANON_KEY"]
DIR  = Path(os.environ["LOGOS_DIR"])

def logo_filename(url: str) -> str:
    sha1 = hashlib.sha1(url.encode("utf-8")).hexdigest()[:20]
    path = urllib.parse.urlparse(url).path
    dot  = path.rfind(".")
    ext  = path[dot + 1:].lower()[:5] if 0 < dot < len(path) - 1 else "img"
    return f"logo_{sha1}.{ext}"

def get(path):
    req = Request(f"{BASE}/rest/v1/{path}")
    req.add_header("apikey", KEY)
    req.add_header("Authorization", f"Bearer {KEY}")
    with urlopen(req, timeout=30) as r:
        return json.loads(r.read())

try:
    urls, offset = set(), 0
    while True:
        q = urllib.parse.urlencode({"select": "logoUrl", "logoUrl": "not.is.null",
                                    "limit": 1000, "offset": offset})
        rows = get(f"races?{q}")
        for row in rows:
            if row.get("logoUrl"):
                urls.add(row["logoUrl"])
        if len(rows) < 1000:
            break
        offset += 1000
except Exception as e:
    print(f"BundledLogos: no se pudo listar logos ({e}); build sigue con red.", file=sys.stderr)
    sys.exit(0)

downloaded = skipped = errors = 0
for url in sorted(urls):
    dest = DIR / logo_filename(url)
    if dest.exists():
        skipped += 1
        continue
    try:
        req = Request(url, headers={"User-Agent": "CalendarioCiclismo-CI/1.0"})
        with urlopen(req, timeout=30) as r:
            dest.write_bytes(r.read())
        downloaded += 1
    except Exception as e:
        errors += 1

print(f"BundledLogos: descargados {downloaded} | en caché {skipped} | fallidos {errors}")
PYEOF

echo "BundledLogos step done"

